class AddNewsaToCategory < ActiveRecord::Migration
  def change
    add_column :categories, :newsa, :boolean
    add_column :categories, :newsb, :boolean
    add_column :categories, :newsc, :boolean
    add_column :categories, :newsd, :boolean
    add_column :categories, :newse, :boolean
    add_column :categories, :newsf, :boolean
    add_column :categories, :newsg, :boolean
    add_column :categories, :newsh, :boolean
    add_column :categories, :vocabularya, :boolean
    add_column :categories, :vocabularyb, :boolean
    add_column :categories, :vocabularyc, :boolean
    add_column :categories, :vocabularyd, :boolean
    add_column :categories, :vocabularye, :boolean
    add_column :categories, :vocabularyf, :boolean
    add_column :categories, :vocabularyg, :boolean
    add_column :categories, :vocabularyh, :boolean
    add_column :categories, :quiza, :boolean
    add_column :categories, :quizb, :boolean
    add_column :categories, :quizc, :boolean
    add_column :categories, :quizd, :boolean
    add_column :categories, :quize, :boolean
    add_column :categories, :quizf, :boolean
    add_column :categories, :quizg, :boolean
    add_column :categories, :quizh, :boolean
    add_column :categories, :musica, :boolean
    add_column :categories, :musicb, :boolean
    add_column :categories, :musicd, :boolean
    add_column :categories, :musicc, :boolean
    add_column :categories, :musice, :boolean
    add_column :categories, :musicf, :boolean
    add_column :categories, :musicg, :boolean
    add_column :categories, :musich, :boolean
    add_column :categories, :grammara, :boolean
    add_column :categories, :grammarb, :boolean
    add_column :categories, :grammarc, :boolean
    add_column :categories, :grammard, :boolean
    add_column :categories, :grammare, :boolean
    add_column :categories, :grammarf, :boolean
    add_column :categories, :grammarg, :boolean
    add_column :categories, :grammarh, :boolean
  end
end
